# Generated by Django 4.0.4 on 2022-05-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
