# Generated by Django 4.0.4 on 2022-05-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='creators_pic',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
