# Generated by Django 4.0.4 on 2022-05-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfume_name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=350)),
                ('price', models.FloatField()),
                ('comment', models.CharField(max_length=500)),
                ('createdBy', models.DateTimeField()),
                ('creationDate', models.DateTimeField()),
                ('perfume_image', models.CharField(max_length=4000)),
            ],
        ),
    ]
