# Generated by Django 4.0.4 on 2022-05-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='creationDate',
        ),
    ]
