# Generated by Django 4.0.4 on 2022-05-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('perfumes', '0002_remove_perfume_createdby_remove_perfume_creationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='brand',
        ),
        migrations.AddField(
            model_name='perfume',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='brands.brand'),
        ),
    ]
