# Generated by Django 4.0.4 on 2022-05-10 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfumes', '0003_remove_perfume_brand_perfume_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notes',
            field=models.CharField(max_length=20),
        ),
    ]
