# Generated by Django 4.0.4 on 2022-05-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0005_rename_createdby_perfume_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='notes',
            field=models.CharField(default='N/A', max_length=400),
        ),
    ]
