# Generated by Django 4.0.4 on 2022-05-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0007_alter_perfume_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
