# Generated by Django 4.0.4 on 2022-05-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0010_alter_perfume_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='notes',
            field=models.CharField(default='N/A', max_length=400),
        ),
    ]
